name: find-n-rock

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm i

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peterbfoo/find-n-rock:ci-${{ github.run_number }}, peterbfoo/find-n-rock:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Update Server's Docker Image
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key "$SSH_USER@$SSH_HOST" 'docker compose pull front && docker compose up -d --no-deps front'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.HOST }}
